const teams = {
  1: {
    id: 1,
    teamName: "Kokomo Wildkats",
    headCoach: "Bob Waddell",
    assistiantCoach: "Timmy Jimmy Bobby",
    athleticDirector: "Jason Snider",
    city: "Kokomo",
    state: "Indiana",
    isMaleTeam: true,
    abbreviation: "KHS",
    players: {
      1: {
        id: 1,
        fname: "Abram",
        lname: "Stamper",
        homeNumber: 1,
        awayNumber: 1,
        position: 'F',
        height: '6\' 11"',
        weight: 120,
        class: "So",
        isActive: true
      },
      2: {
        id: 2,
        fname: "Patrick",
        lname: "Barrett",
        homeNumber: 2,
        awayNumber: 2,
        position: 'F',
        height: '6\' 11"',
        weight: 120,
        class: "So",
        isActive: true
      },
      3: {
        id: 3,
        fname: "Trajan",
        lname: "Deckard",
        homeNumber: 4,
        awayNumber: 4,
        position: 'G',
        height: '6\' 11"',
        weight: 120,
        class: "So",
        isActive: true
      },
      4: {
        id: 4,
        fname: "Anthony",
        lname: "Barnard",
        homeNumber: 23,
        awayNumber: 23,
        position: 'PF',
        height: '6\' 11"',
        weight: 120,
        class: "Sr",
        isActive: true
      },
      5: {
        id: 5,
        fname: "Kyle",
        lname: "Wade",
        homeNumber: 40,
        awayNumber: 40,
        position: 'C',
        height: '5\' 10"',
        weight: 300,
        class: "Sr",
        isActive: true
      },
      6: {
        id: 6,
        fname: "Nate",
        lname: "Hemmerich",
        homeNumber: 50,
        awayNumber: 50,
        position: 'C',
        height: '7\' 2"',
        weight: 250,
        class: "Sr",
        isActive: true
      },
      7: {
        id: 7,
        fname: "Julian",
        lname: "Wallace",
        homeNumber: 5,
        awayNumber: 5,
        position: 'SG',
        height: '6\' 11"',
        weight: 120,
        class: "Fr",
        isActive: true
      },
      8: {
        id: 8,
        fname: "Jeremy",
        lname: "Baker",
        homeNumber: 0,
        awayNumber: 0,
        position: 'F',
        height: '6\' 11"',
        weight: 120,
        class: "Jr",
        isActive: true
      },
      9: {
        id: 9,
        fname: "Steven",
        lname: "Edwards",
        homeNumber: 2,
        awayNumber: 2,
        position: 'F',
        height: '6\' 11"',
        weight: 120,
        class: "So",
        isActive: false
      },
      10: {
        id: 10,
        fname: "Shemar",
        lname: "Robinson",
        homeNumber: 3,
        awayNumber: 3,
        position: 'PF',
        height: '6\' 11"',
        weight: 200,
        class: "Fr",
        isActive: true
      }
    }
  },
  2: {
    id: 2,
    teamName: "Fishers HS",
    headCoach: "Matt Moore",
    assistiantCoach: "Timmy Jimmy Bobby",
    athleticDirector: "Jason Snider",
    city: "Fishers",
    state: "Indiana",
    isMaleTeam: true,
    abbreviation: "FHS",
    players: {
      11: {
        id: 11,
        fname: "Phil",
        lname: "Warman",
        homeNumber: 0,
        awayNumber: 0,
        position: 'PF',
        height: '6\' 11"',
        weight: 200,
        class: "Fr",
        isActive: true
      },
      12: {
        id: 12,
        fname: "Caleb",
        lname: "Barrett",
        homeNumber: 1,
        awayNumber: 1,
        position: 'PF',
        height: '6\' 11"',
        weight: 200,
        class: "Fr",
        isActive: true
      },
      13: {
        id: 13,
        fname: "Willie",
        lname: "Jackson",
        homeNumber: 5,
        awayNumber: 5,
        position: 'SG',
        height: '6\' 11"',
        weight: 200,
        class: "Sr",
        isActive: true
      },
      14: {
        id: 14,
        fname: "Emmanuel",
        lname: "Davis",
        homeNumber: 10,
        awayNumber: 10,
        position: 'PG',
        height: '6\' 11"',
        weight: 200,
        class: "Sr",
        isActive: true
      },
      15: {
        id: 15,
        fname: "Jeremy",
        lname: "Szilagyi",
        homeNumber: 21,
        awayNumber: 21,
        position: 'PF',
        height: '5\' 11"',
        weight: 200,
        class: "FR",
        isActive: true
      },
      16: {
        id: 16,
        fname: "Bryce",
        lname: "Gee",
        homeNumber: 25,
        awayNumber: 25,
        position: 'C',
        height: '6\' 11"',
        weight: 200,
        class: "Jr",
        isActive: true
      },
      17: {
        id: 17,
        fname: "Craig",
        lname: "Yoho",
        homeNumber: 32,
        awayNumber: 32,
        position: 'F',
        height: '5\' 7"',
        weight: 200,
        class: "Sr",
        isActive: true
      },
      18: {
        id: 18,
        fname: "Jack",
        lname: "Maller",
        homeNumber: 40,
        awayNumber: 40,
        position: 'C',
        height: '6\' 7"',
        weight: 250,
        class: "Sr",
        isActive: true
      },
      19: {
        id: 19,
        fname: "Alex",
        lname: "Szilagyi",
        homeNumber: 12,
        awayNumber: 14,
        position: 'F',
        height: '6\' 1"',
        weight: 200,
        class: "So",
        isActive: false
      },
      20: {
        id: 20,
        fname: "Brendhan",
        lname: "Russom",
        homeNumber: 34,
        awayNumber: 34,
        position: 'PF',
        height: '6\' 0"',
        weight: 220,
        class: "Fr",
        isActive: true
      }
    }
  }
}

export default teams;